<?php
/**
 * German language pack for MyBB 1.8 (informal)
 * Deutsches Sprachpaket für MyBB 1.8 "informell" (Du)
 * (c) 2005-2014 MyBBoard.de
 * 
 * Author/Autor: http://www.mybboard.de/
 * License/Lizenz: GNU Lesser General Public License, Version 3
 */

$l['user_groups'] = "Benutzergruppen";
$l['manage_user_groups'] = "Benutzergruppen verwalten";
$l['manage_user_groups_desc'] = "Hier kannst du die verschiedenen Benutzergruppen deines Forums verwalten. Außerdem kannst du die Anzeigereihenfolge von Team-Gruppen auf der Foren-Team-Seite einstellen. Die Gruppen werden alphabetisch sortiert, wenn du bei allen \"0\" angibst. Um die Reihenfolge zu ändern, musst du das Formular unten auf der Seite absenden.";
$l['add_user_group'] = "Neue Benutzergruppe hinzufügen";
$l['add_user_group_desc'] = "Hier kannst du neue Benutzergruppen erstellen und optional die Berechtigungen von anderen Gruppen kopieren. Nach dem Sichern der Gruppe, wirst du zur vollen Bearbeitungsseite weitergeleitet.";
$l['group_join_requests'] = "Beitrittsanfragen";
$l['group_join_requests_desc'] = "Unten werden alle Benutzer aufgeführt, die der Gruppe beitreten wollen. Von hier aus, kannst du die Anfrage entweder akzeptieren oder ablehnen.";
$l['manage_group_leaders'] = "Gruppenleiter verwalten";
$l['manage_group_leaders_desc'] = "Hier kannst du die Gruppenleiter für diese Gruppe verwalten. Abhängig von der Einstellungen für die Leiter, können die Benutzer die Mitglieder der Gruppe verwalten und die Beitrittsanfragen moderieren, wenn die Gruppe öffentlich zugänglich ist.";
$l['edit_user_group'] = "Benutzergruppe bearbeiten";
$l['edit_user_group_desc'] = "Hier kannst du eine bestehende Benutzergruppe bearbeiten.";
$l['edit_group_leader'] = "Gruppenleiter bearbeiten";
$l['edit_group_leader_desc'] = "Hier kannst du die Berechtigungen für den Gruppenleiter bearbeiten.";
$l['group_leaders'] = "Gruppenleiter";

$l['delete_group'] = "Gruppe löschen";
$l['edit_group'] = "Gruppe bearbeiten";
$l['no_groups'] = "Es gibt im Moment keine Benutzergruppen in deinem Forum";
$l['join_requests'] = "Beitrittsanfragen moderieren";
$l['update_groups_order'] = "Anzeigereihenfolge aktualisieren";
$l['reset'] = "Zurücksetzen";
$l['number_of_users'] = "# der Benutzer";
$l['order'] = "Reihenfolge";
$l['group'] = "Gruppe";
$l['custom_user_group'] = "Eigene Benutzergruppe";
$l['default_user_group'] = "Standard-Benutzergruppe";
$l['join_requests_for'] = "Beitrittsanfragen für";
$l['users'] = "Benutzer";
$l['reason'] = "Grund";
$l['date_requested'] = "Datum der Anfrage";
$l['approve'] = "Akzeptieren";
$l['deny'] = "Ablehnen";
$l['approve_selected_requests'] = "Ausgewählte Anfragen akzeptieren";
$l['deny_selected_requests'] = "Ausgewählte Anfragen ablehnen";
$l['group_leaders_for'] = "Gruppenleiter für";
$l['can_manage_members'] = "Kann Mitglieder verwalten?";
$l['can_manage_join_requests'] = "Kann Beitrittsanfragen verwalten?";
$l['can_invite_members'] = "Kann Mitglieder einladen?";
$l['user'] = "Benutzer";
$l['can_manage_group_members'] = "Kann Gruppenmitglieder verwalten?";
$l['can_manage_group_members_desc'] = "Soll der Benutzer die Mitglieder der Gruppen verwalten dürfen?";
$l['can_manage_group_join_requests'] = "Kann Beitrittsanfragen verwalten?";
$l['can_manage_group_join_requests_desc'] = "Soll dieser Benutzer die Beitrittsanfragen für diese Gruppe akzeptieren oder ablehnen können?";
$l['can_invite_group_members'] = "Kann Gruppenmitglieder einladen?";
$l['can_invite_group_members_desc'] = "Soll der Benutzer neue Mitglieder in diese Gruppe einladen dürfen?";
$l['make_user_member'] = "Benutzer zur Gruppe hinzufügen?";
$l['make_user_member_desc'] = "Soll dieser Benutzer als Mitglied zu dieser Gruppe hinzugefügt werden, sofern er nicht bereits Gruppenmitglied ist?";
$l['add_group_leader'] = "Gruppenleiter hinzufügen zu";
$l['save_group_leader'] = "Gruppenleiter speichern";
$l['edit_leader'] = "Leiter bearbeiten:";
$l['title'] = "Titel";
$l['short_description'] = "Kurze Beschreibung";
$l['username_style'] = "Benutzernamen-Stil";
$l['username_style_desc'] = "Das erlaubt dir, Benutzern, die diese Gruppe als Anzeigegruppe gewählt haben, einen speziellen Namens-Stil zu geben.<br /><strong>Bitte benutze {username} um den Namen zu einzusetzen.</strong>";
$l['user_title'] = "Standard-Benutzertitel";
$l['user_title_desc'] = "Wenn leer, wird das Benutzertitel-System verwendet, um den Titel anzuzeigen.";
$l['do_not_copy_permissions'] = "Keine Berechtigungen kopieren";
$l['copy_permissions_from'] = "Kopiere Berechtigungen von...";
$l['copy_permissions_from_desc'] = "Wenn du willst, kannst du die Foren- und Gruppenberechtigungen von einer anderen Gruppe kopieren. Um dies zu nutzen, wähle eine Gruppe.";
$l['save_user_group'] = "Benutzergruppe speichern";
$l['list_users'] = "Benutzer auflisten";

$l['general'] = "Allgemein";
$l['forums_posts'] = "Foren und Beiträge";
$l['users_permissions'] = "Benutzer und Berechtigungen";
$l['misc'] = "Sonstiges";
$l['mod_cp'] = "Moderator-CP";
$l['stars'] = "Anzahl der Sterne";
$l['star_image'] = "Sternenbild";
$l['user_stars'] = "Benutzer-Sterne";
$l['user_stars_desc'] = "Wenn du die Anzahl der Sterne und den Ort des Sternenbild eingegeben hast, werden diese Sterne für diese Benutzergruppe verwendet. Die Anzahl der Sterne gilt nur, wenn der Benutzertitel nicht leer ist.";
$l['group_image'] = "Gruppenbild";
$l['group_image_desc'] = "Hier kannst du ein Gruppenbild einstellen, das in jedem Beitrag jedes Benutzers dieser Gruppe angezeigt wird. Bitte benutze <strong>{lang}</strong> um übersetzte Gruppenbilder in der Sprache des Benutzers anzuzeigen, wenn diese vorhanden sind.";
$l['general_options'] = "Allgemeine Optionen";
$l['member_list'] = "Wird auf der Mitglieder-Liste angezeigt";
$l['forum_team'] = "Zeige auf der Foren-Team-Seite";
$l['is_banned_group'] = "Zur Ausschlussgruppe zugehörig?<br /><small>Wenn ja, ist es möglich, Benutzer dieser Gruppe aus dem Forum auszuschließen.</small>";
$l['publicly_joinable_options'] = "Einstellungen für den öffentlichen Zugang";
$l['user_joinable'] = "Benutzer können dieser Gruppe beitreten";
$l['moderate_join_requests'] = "Neue Beitritte müssen moderiert werden<br /><small>Für diese Option müssen Benutzer dieser Gruppe beitreten können.</small>";
$l['invite_only'] = "Benutzer müssen eingeladen werden um dieser Gruppe beitreten zu können<br /><small>Für diese Option müssen Benutzer dieser Gruppe beitreten können.</small>";
$l['can_set_as_display_group'] = "Benutzer können diese Gruppe als Anzeigegruppe auswählen<br /><small>Wenn ja, können die Benutzer diese Gruppe als Anzeigegruppe für Benutzertitel, Sterne, Benutzernamen-Stil und Gruppenbilder auswählen.</small>";
$l['moderation_administration_options'] = "Berechtigungen: Administration / Moderation";
$l['is_super_mod'] = "Ist Super Moderator";
$l['can_access_mod_cp'] = "Kann Moderator-CP betreten";
$l['can_access_admin_cp'] = "Kann Admin-CP betreten";
$l['viewing_options'] = "Berechtigungen: Sehen";
$l['can_view_board'] = "Kann Forum betreten";
$l['can_view_threads'] = "Kann Themen sehen";
$l['can_search_forums'] = "Kann Foren durchsuchen";
$l['can_view_profiles'] = "Kann Profile sehen";
$l['can_download_attachments'] = "Kann Attachments herunterladen";
$l['can_view_board_closed'] = "Kann das Forum auch betrachten, wenn es geschlossen ist?";
$l['posting_rating_options'] = "Berechtigungen: Beiträge erstellen / Themen bewerten";
$l['can_post_threads'] = "Kann Themen eröffnen";
$l['can_post_replies'] = "Kann Antworten erstellen";
$l['can_rate_threads'] = "Kann Themen bewerten";
$l['moderation_options'] = "Berechtigungen: Moderation";
$l['mod_new_posts'] = "Neue Beiträge moderieren?";
$l['mod_new_threads'] = "Neue Themen moderieren?";
$l['mod_new_attachments'] = "Neue Attachments moderieren?";
$l['mod_after_edit'] = "Beiträge nach der Bearbeitung moderieren?";
$l['poll_options'] = "Berechtigungen: Umfragen";
$l['max_posts_per_day'] = "Maximale Beiträge pro Tag";
$l['max_posts_per_day_desc'] = "Gib hier die Anzahl der Beiträge an, die ein Benutzer dieser Gruppe pro Tag höchstens schreiben darf (0 = unendlich).";
$l['can_post_polls'] = "Kann Umfragen erstellen";
$l['can_vote_polls'] = "Kann an Umfragen teilnehmen";
$l['can_undo_votes'] = "Kann Stimme bei einer Abstimmung zurücknehmen?";
$l['attachment_options'] = "Berechtigungen: Attachments";
$l['can_post_attachments'] = "Kann Attachments veröffentlichen";
$l['attach_quota'] = "Attachment-Limit:";
$l['attach_quota_desc'] = "Hier kannst du das Attachment-Limit einstellen, das für jeden Benutzer der Gruppe gilt (0 = unendlich).";
$l['editing_deleting_options'] = "Berechtigungen: Bearbeiten / Löschen";
$l['can_edit_posts'] = "Kann eigene Beiträge bearbeiten";
$l['can_delete_posts'] = "Kann eigene Beiträge löschen";
$l['can_delete_threads'] = "Kann eigene Themen löschen";
$l['can_edit_attachments'] = "Kann eigene Attachments aktualisieren";
$l['can_view_deletion_notices'] = "Kann Lösch-Hinweise sehen?";
$l['account_management'] = "Berechtigungen: Accounts verwalten";
$l['edit_time_limit'] = "Bearbeitungs-Limit";
$l['edit_time_limit_desc'] = "Der Zeitraum in Minuten, bevor Benutzer ihre Beiträge nicht mehr bearbeiten können, falls sie die nötigen Rechte haben (0 = unendlich).";
$l['can_be_reported'] = "Kann gemeldet werden (Profil, Beiträge, Bewertungen)?";
$l['can_access_usercp'] = "Kann Benutzer-CP betreten";
$l['can_change_username'] = "Kann Benutzernamen wechseln";
$l['can_change_website'] = "Kann Homepage ändern";
$l['can_use_usertitles'] = "Kann eigene Benutzertitel verwenden";
$l['can_upload_avatars'] = "Kann Avatare hochladen";
$l['can_use_signature'] = "Kann Signatur angeben?";
$l['can_use_signature_posts'] = "Kann Signatur nach x Beiträgen angeben?";
$l['required_posts'] = "Benötigte Beitragsanzahl um eine Signatur anzugeben:";
$l['required_posts_desc'] = "Hier kannst du die minimale Beitragsanzahl angeben, bevor sie eine Signatur angeben können (0 = keine Beschränkung).";
$l['uses_no_follow'] = "Links in Signaturen werden mit nofollow versehen?";
$l['reputation_system'] = "Bewertungs-System";
$l['can_use_pms'] = "Kann das Private Nachrichten-System nutzen";
$l['can_send_pms'] = "Kann Private Nachrichten versenden";
$l['can_track_pms'] = "Kann Private Nachrichten verfolgen";
$l['can_deny_reciept'] = "Kann PN-Empfangsbestätigungen ablehnen";
$l['can_override_pms'] = "Kann Private Nachrichten senden, auch wenn der Empfänger dies deaktiviert hat";
$l['message_quota'] = "Nachrichten-Quota";
$l['message_quota_desc'] = "Hier kannst du die maximale Anzahl von speicherbaren PNs für diese Gruppe setzen. Wenn leer, können Benutzer unendlich viele PNs speichern.";
$l['max_recipients'] = "Maximale Empfänger pro Nachricht";
$l['max_recipients_desc'] = "Maximale Anzahl an Empfängern, an die ein Benutzer eine Private Nachricht senden können. Wenn leer, können unendlich viele Empfänger pro Nachricht eingegeben werden.";
$l['show_reputations'] = "Zeige Bewertungen für Benutzer dieser Gruppe";
$l['can_give_reputation'] = "Kann Benutzer bewerten";
$l['can_delete_own_reputation'] = "Kann selbst abgegebene Bewertungen löschen?";
$l['points_to_award_take'] = "Punkte zur Bewertung hinzufügen/abziehen:";
$l['points_to_award_take_desc'] = "Hier kannst du einstellen wie viele Punkte ein Benutzer einem anderen hinzufügen/abziehen kann.";
$l['max_reputations_daily'] = "Maximale Bewertungen pro Tag:";
$l['max_reputations_daily_desc'] = "Gib hier die Anzahl der Bewertungen an, die ein Benutzer dieser Gruppe pro Tag höchstens geben darf (0 = unendlich).";
$l['max_reputations_perthread'] = "Maximale Bewertungen pro Thema:";
$l['max_reputations_perthread_desc'] = "Wenn 'Beitragsbewertungen erlauben' aktiv ist, kannst du hier die Anzahl der Bewertungen angeben, die ein Benutzer dieser Gruppe einem anderen Benutzer in einem Thema am selben Tagen höchstens geben darf (0 = unendlich).";
$l['max_reputations_peruser'] = "Maximale Bewertungen pro Benutzer:";
$l['max_reputations_peruser_desc'] = "Gib hier die Anzahl der Bewertungen an, die ein Benutzer dieser Gruppe einem anderen Benutzer höchstens geben darf (0 = unendlich).";
$l['warning_system'] = "Verwarn-System";
$l['can_send_warnings'] = "Kann andere Benutzer verwarnen";
$l['can_receive_warnings'] = "Kann verwarnt werden";
$l['warnings_per_day'] = "Maximale Verwarnungen pro Tag:";
$l['private_messaging'] = "Private Nachrichten";
$l['calendar'] = "Kalender";
$l['can_view_calendar'] = "Kann Kalender sehen";
$l['can_post_events'] = "Kann Termine eintragen";
$l['can_bypass_event_moderation'] = "Termine müssen moderiert werden";
$l['can_moderate_events'] = "Kann Termine moderieren";
$l['whos_online'] = "Wer ist online";
$l['can_view_whos_online'] = "Kann sehen, wer online ist";
$l['can_view_invisible'] = "Kann unsichtbare Benutzer sehen";
$l['can_view_ips'] = "Kann IP-Adressen sehen";
$l['can_view_member_list'] = "Kann Benutzerliste sehen";
$l['show_in_birthday_list'] = "Wird in der Geburtstags-Liste angezeigt";
$l['can_email_users'] = "Kann Themen an Freunde senden und E-Mails an Benutzer senden";
$l['can_email_users_override'] = "Kann E-Mails an Benutzer senden, selbst wenn sie auf deren Ignorier-Liste stehen?";
$l['max_emails_per_day'] = "Maximale E-Mails pro Tag:";
$l['max_emails_per_day_desc'] = "Die maximale Anzahl, die Benutzer über die 'Thema einem Freund senden'- und die 'E-Mail an Benutzer schicken'-Funktion senden können. (0=keine Begrenzung)";
$l['email_flood_time'] = "Zeit zwischen E-Mails:";
$l['email_flood_time_desc'] = "Die Anzahl an Minuten, die ein Benutzer nach dem Senden einer E-Mail warten muss, bevor er eine weitere absenden kann. (0=keine Wartezeit)";
$l['forum_post_options'] = "Foren &amp; Beiträge";
$l['user_options'] = "Benutzer";
$l['can_manage_announce'] = "Können Ankündigungen verwalten?<br /><small>Bitte beachte, dass Moderatoren mindestens einem Forum hinzugefügt worden sein müssen um Ankündigungen bearbeiten zu können.</small>";
$l['can_manage_mod_queue'] = "Können Moderations-Warteschlange verwalten?<br /><small>Bitte beachte, dass Moderatoren mindestens einem Forum hinzugefügt worden sein müssen um die Moderations-Warteschlange verwalten zu können.</small>";
$l['can_manage_reported_content'] = "Können Meldungen verwalten?<br /><small>Bitte beachte, dass Moderatoren mindestens einem Forum hinzugefügt worden sein müssen um die Meldungen verwalten zu können.</small>";
$l['can_view_mod_logs'] = "Können Moderatoren-Protokoll ansehen?<br /><small>Bitte beachte, dass Moderatoren mindestens einem Forum hinzugefügt worden sein müssen um das Moderatoren-Protokoll ansehen zu können.</small>";
$l['can_edit_profiles'] = "Können Profile bearbeiten?<br /><small>Bitte beachte, dass Moderatoren die Profile von Super-Moderatoren und Administratoren nicht bearbeiten können.</small>";
$l['can_ban_users'] = "Kann Benutzer sperren?<br /><small>Bitte beachte, dass Moderatoren Super-Moderatoren und Administratoren nicht sperren können.</small>";
$l['can_view_warnlogs'] = "Kann Warnungs-Protokoll ansehen?";
$l['can_use_ipsearch'] = "Kann IP-Adressen suchen?";
$l['outstanding_join_request'] = "ausstehenden Beitrittsanfragen";

$l['no_join_requests'] = "Es gibt zur Zeit keine ausstehenden Beitrittsanfragen.";
$l['no_assigned_leaders'] = "Du hast bisher keinen Leiter dieser Gruppe zugewiesen. Um dieser Gruppe einen Leiter hinzuzufügen, füllen das Formular unten aus.";

$l['error_missing_title'] = "Du hast keinen Titel für diese neue Benutzergruppe eingegeben.";
$l['error_invalid_user_group'] = "Die ausgewählte Benutzergruppe ist ungültig.";
$l['error_invalid_join_request'] = "Du hast eine ungültige Beitrittsanfrage ausgewählt.";
$l['error_invalid_username'] = "Der eingegebene Benutzername ist ungültig";
$l['error_already_leader'] = "Der Benutzer ist bereits ein Leiter dieser Benutzergruppe.";
$l['error_invalid_group_leader'] = "Du hast einen ungültigen Gruppenleiter ausgewählt.";
$l['error_missing_namestyle_username'] = "Der Benutzernamen-Stil muss {username} enthalten";
$l['error_disallowed_namestyle_username'] = "Du kannst die Elemente script, meta und base nicht beim Benutzernamen-Stil verwenden.";
$l['error_default_group_delete'] = "Standard-Benutzergruppen können nicht gelöscht werden";
$l['error_cannot_have_both_types'] = "Die Beitritte in eine Gruppe können nicht gleichzeitig Einladungen benötigen und moderiert werden. Bitte wähle entweder die eine Option oder die andere.";

$l['success_group_created'] = "Die neue Benutzergruppe wurde erfolgreich erstellt.";
$l['success_group_updated'] = "Die Benutzergruppe wurde erfolgreich aktualisiert.";
$l['success_group_created_duplicate_title'] = "Die neue Benutzergruppe wurde erfolgreich erstellt. Bitte beachte, dass es mehrere Benutzergruppen mit dem Namen \"{1}\" gibt.";
$l['success_group_updated_duplicate_title'] = "Die Benutzergruppe wurde erfolgreich aktualisiert. Bitte beachte, dass es mehrere Benutzergruppen mit dem Namen \"{1}\" gibt.";
$l['success_group_deleted'] = "Die ausgewählte Benutzergruppe wurde erfolgreich gelöscht.";
$l['success_groups_disporder_updated'] = "Die Anzeigereihenfolge wurde erfolgreich aktualisiert.";
$l['success_join_request_approved'] = "Die Beitrittsanfrage wurde erfolgreich akzeptiert. Der Benutzer ist nun Teil dieser Gruppe.";
$l['success_join_request_denied'] = "Die Beitrittsanfrage wurde erfolgreich abgelehnt.";
$l['success_selected_requests_approved'] = "Die ausgewählte Beitrittsanfrage wurde erfolgreich akzeptiert. Der Benutzer ist nun Teil dieser Gruppe.";
$l['success_selected_requests_denied'] = "Die ausgewählte Beitrittsanfrage wurde erfolgreich abgelehnt.";
$l['success_user_made_leader'] = "wurde erfolgreich zum Leiter dieser Gruppe gemacht.";
$l['success_group_leader_updated'] = "Der Gruppenleiter wurde erfolgreich aktualisiert.";
$l['success_group_leader_deleted'] = "Der Benutzer wurde erfolgreich aus der Liste der Gruppenleiter dieser Gruppe entfernt.";

$l['confirm_group_deletion'] = "Willst du diese Gruppe wirklich löschen?";
$l['confirm_group_leader_deletion'] = "Willst du wirklich diesen Gruppenleiter löschen?";
